### PR TITLE
Visualize the results of the division of the data set

### PR DESCRIPTION
**Pull request by NigeloYang**
The `show_data_distribution.py` shows in a visual way how discrete the dataset is after running `generate_mnist.py noniid - dir` (`alpha = 0.1` for the Dirichlet distribution in `./dataset/utils/dataset_utils.py`)

### CODE REVIEW

**Review by TsingZ0 — COMMENTED** [review]
Can you provide some examples such as the command line to run the visualization code?

**Review by TsingZ0 — CHANGES_REQUESTED** [review]
Can you provide some examples and instructions in `README.md`, such as the command line to run the visualization code and the result figure?

**Comment by NigeloYang** [comment]
In the new merge request, a description and picture are added to the README.md file

**Review by TsingZ0 — CHANGES_REQUESTED** [review]
Based on the final generated 'mnist_partition.png', we can only determine which data labels exist on the clients, rather than obtaining the distribution indicating the quantity of data for each label.

**Pull request closed without merging**
